name 'basic-lamp-lemp'
maintainer 'Artist IO'
maintainer_email 'artist.io@outlook.com'
license 'GPL 2'
description 'Installs/Configures basic-lamp-lemp'
long_description 'Installs/Configures basic-lamp-lemp'
version '0.1.13'

depends 'apt', '~> 2.9.2'
depends 'httpd', '~> 0.3.3'
depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'mysql', '~> 6.0.17'
depends 'php5-fpm', '~> 0.4.6' 
